### PR TITLE
 TDD_RSpec Tic Tac Toe 

### PR DESCRIPTION
**Pull request by kcotrinam**
**In this part of the project we:**
- Added RSpec files.
- Added +20 different cases for testing the Tic Tac Toe game.

### CODE REVIEW

**Comment by kcotrinam** [comment]
This is a fork from the original repository worked with my previous partner 'Alvaro', now used to work for the test project.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @kcotrinam and @SunnySparks :balloon: :lollipop: 

### Thank you for your submission :handshake: :handshake: your test cases look great :ok_hand: I think you've done a great job with them and you really understood what was wanted with this project so excellent work :clap: :clap: :clap: there are a few changes to make so let's work on them :construction: :construction_worker: :construction_worker: 

#### OOP good practices

- [x] Good file naming

> I see that within the file `lib/game_logic.rb` you have both the Board and Player classes, this is not correct each of the classes should be put in a file that holds their name so `lib/board.rb` and `lib/player.rb` respectively, same goes for your test cases you should create a `spec/board_spec.rb` and a `spec/player.rb` file

#### Project specific

> I see you only have one negative it block for your update Board method but let's add a couple more negative test cases

- [x] specs cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

#### General

- [x] Let's add a section in your Readme file that explains how to properly run your test cases with Rspec

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by kcotrinam** [comment]
- The game_logic file was divided into two different files, so each class has its own file. 
- We added more cases for testing negative. 
- README file was modified to add instructions for running tests

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Well done guys, your project is complete.

now you can merge to development your project is approved.

## Happy Coding :tophat:

**Pull request merged**
